name: Release
permissions:
  packages: write
  contents: write
on:
  push: 
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
      KAMAL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: kamal.reidodon.net
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create context
        run: docker context create remote --docker "host=ssh://root@kamal.reidodon.net"
      - name: Test context
        run: |
          docker context use remote
          docker context ls
          docker ps
          docker compose ls
          docker context use default
          
        

