name: Release
permissions:
  packages: write
  contents: write
on:
  push: 
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
      KAMAL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create context
        run: docker context create remote --docker "host=ssh://root@kamal.reidodon.net"
        
      - name: Run remote db migrations
        uses: appleboy/ssh-action@v0.1.5
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        with:
          host: kamal.reidodon.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: APPTOKEN,USERNAME
          script: |
            set -e
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
