name: Release
permissions:
  packages: write
  contents: write
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
      KAMAL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan -H kamal.reidodon.net >> ~/.ssh/known_hosts

      - name: Create Docker context
        run: docker context create remote --docker "host=ssh://root@kamal.reidodon.net"

      - name: Test remote context
        run: docker --context remote ps
        
      - name: Build and push image
        run: docker --context remote build -t ghcr.io/layoric/kamal2:latest .
          